services:
  - type: web
    name: reddit-persona-api
    env: python
    region: oregon
    branch: main
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: reddit-persona-ui
    env: python
    region: oregon
    branch: main
    buildCommand: |
      cd frontend
      pip install -r requirements.txt
    startCommand: |
      cd frontend
      python app.py
