# render.yaml

services:
  - type: web
    name: reddit-persona-api
    env: python
    region: oregon
    branch: main
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDDIT_CLIENT_ID
      - key: REDDIT_CLIENT_SECRET
      - key: REDDIT_USER_AGENT
      - key: OPENAI_API_KEY

  - type: web
    name: reddit-persona-ui
    env: python
    region: oregon
    branch: main
    buildCommand: |
      cd frontend
      pip install -r requirements.txt
    startCommand: |
      cd frontend
      python app.py
    envVars:
      - key: BACKEND_URL        # set to your API’s Render URL, e.g. https://reddit-persona-api.onrender.com

staticSites: []  # you’re not serving static-only sites here
